# Generated by Django 3.0.7 on 2020-07-08 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=30, unique=True, verbose_name='索引'),
            preserve_default=False,
        ),
    ]
